### ISSUE TITLE
array arguments are interpreted as float

### ISSUE THREAD

**Issue by skenqbx** [bcoe/yargs#166]
```js
'use strict';
var yargs = require('yargs');

var argv = yargs
    .option('v', {
      type: 'array'
    })
    .argv;

console.log(argv.v);
```
Given the simple script I get the following output;
```
$ node test.js -v 0.10 -v 0.12
[ 0.1, 0.12 ]
```

```
$ node test.js -v "0.10" -v "0.12"
[ 0.1, 0.12 ]
```

This is reproducible with v3.9.1 & v3.10.0.

Question: Would it be possible to configure a type for the array arguments?

**Comment by bcoe** [comment]
perhaps something like this?

```js
var argv = require('yargs')
  .array('v', {type: 'string'}
```
The caveat being you'd have to use the `array` method rather than the `option` shorthand.

**Comment by skenqbx** [comment]
I like that.

**Comment by nexdrew** [comment]
@skenqbx There hasn't been any movement on this lately, but if you're ok with passing multiple flags (i.e. `-v 0.10 -v 0.12`) you can avoid the float coercion using `type: 'string'` for your option instead of `type: 'array'`:

```
var argv = require('yargs')
  .option('v', {
    type: 'string'
  })
  .argv
console.log(argv.v)
```

```
$ node test.js -v 0.10 -v 0.12
[ '0.10', '0.12' ]
```

The only real benefit of using `type: 'array'` is to support a variable number of arg values for an option without requiring duplicate flags, like:

```
$ node test.js -v 0.10 0.12
[ 0.1, 0.12 ]
```

As you've found, this is where float coercion is a problem.

**Comment by skenqbx** [comment]
@nexdrew I can perfectly work with your solution, thank you!
