### ISSUE TITLE
colors!

### ISSUE THREAD

**Issue by fulmicoton** [bcoe/yargs#251]
That would be awesome if we could get colors in the usage description.

**Comment by nexdrew** [comment]
@fulmicoton Great suggestion! My opinion is that content decoration should be handled outside of `yargs`, so the API can stay focused on functionality. That's why I created [`yargonaut`](https://www.npmjs.com/package/yargonaut).

Originally it only supported decoration via [`figlet`](https://www.npmjs.com/package/figlet) fonts (ASCII Art), but, based on your suggestion, I spent some time today adding support for [`chalk`](https://www.npmjs.com/package/chalk) styles as well. With the latest version of `yargonaut` (1.1.0), you can now colorize the `yargs`-generated text for your CLI! (I can't believe I didn't think of this before! :wink:)

Please give `yargonaut` a try and let us know what you think, one way or another. Hopefully it gives you the flexibility you're looking for. :sunglasses:

Note 1: You'll probably want to focus on the [`helpStyle()`](https://www.npmjs.com/package/yargonaut#helpstyle-style), [`errorsStyle()`](https://www.npmjs.com/package/yargonaut#errorsstyle-style), and [`style()`](https://www.npmjs.com/package/yargonaut#style-style-key) methods.

Note 2: For best results (and full locale support), you should `require('yargonaut')` **before** you `require('yargs')`.

**Comment by bcoe** [comment]
@fulmicoton I'm with @nexdrew on this, colors are a great extension to yargs but I think we should keep it out of core. Seem reasonable?

**Comment by bcoe** [comment]
Perhaps we could add a section to the README that has nifty related projects?

**Comment by nexdrew** [comment]
I thought of that but didn't want to shamelessly advertise my module or make it seem like `yargonaut` is officially endorsed by `yargs`. I'd be happy to add it though.

Personally I think it'd be cool to build support for plugins into `yargs`, but I haven't come up with an API for this yet. Was planning to bring it up when we talk about commands/V4.

**Comment by fulmicoton** [comment]
Sorry for not replying earlier. Thank you so much @nexdrew for picking up on that so quickly. I will try that out later today.

About the discussion of whether to put that in yargs or yargonaut, whatever works for you guys :)

**Comment by bcoe** [comment]
@nexdrew be as shameless as you see fit :)

**Comment by fulmicoton** [comment]
@nexdrew Thank you! It works fine for me. I wondered if it is possible to apply a specific color to option (-f, --file) and commands.

**Comment by nexdrew** [comment]
@fulmicoton The official answer is no, because `yargonaut` can only customize the locale-specific strings baked into `yargs`. Option keys, command names, and descriptions are defined by the consumer module, and so are not subject to internal `y18n` lookup.

However, you *can* hack it via "hidden" commands and options, if you really want to. The code is pretty ugly, and you'll have to duplicate some `yargs` validation logic, but it would look something like this:

```js
var yargonaut = require('yargonaut')
var chalk = yargonaut.chalk() // could also just require('chalk') yourself

var argv = require('yargs')
  .command(chalk.green('add'), 'Add a file')
  .command('add', false, function (yargs) {
    // need option validation here
    console.log('adding')
  })
  .command(chalk.red('rm'), 'Remove a file')
  .command('rm', false, function (yargs) {
    // need option validation here
    console.log('removing')
  })
  .demand(1)
  .option(chalk.yellow('f'), {
    alias: chalk.yellow('file'),
    describe: 'The file to add or remove',
    type: 'string'
  })
  .option('f', {
    alias: 'file',
    type: 'string'
  })
  .help('h').alias('h', 'help').wrap(null)
  .argv
```

![screen shot 2015-09-09 at 12 05 21 pm](https://cloud.githubusercontent.com/assets/1929625/9767220/161c75de-56eb-11e5-8c7d-a231e1043ce2.png)

Your best bet is probably to just color the descriptions instead of the options/commands themselves, like this:

```js
var yargonaut = require('yargonaut')
var chalk = yargonaut.chalk()

var argv = require('yargs')
  .command('add', chalk.green('Add a file'), function (yargs) {
    console.log('adding')
  })
  .command('rm', chalk.red('Remove a file'), function (yargs) {
    console.log('removing')
  })
  .demand(1)
  .option('f', {
    alias: 'file',
    describe: chalk.yellow('The file to add or remove'),
    demand: true,
    type: 'string'
  })
  .help('h').alias('h', 'help').wrap(null)
  .argv
```

![color descriptions](https://cloud.githubusercontent.com/assets/1929625/9766828/faa338bc-56e8-11e5-9846-8fba139ea9de.png)

That's about all you can do for now.

**Comment by binarymist** [comment]
It seems that yargonaut is applying some extra non printable characters? `require('yargonaut').style('green');`

![image](https://user-images.githubusercontent.com/2862029/41075396-8fcc193a-6a60-11e8-87af-c0038c5651bb.png)

How would you go about applying an rgb hex to the headgins alone (Commands, Options), and then a different styl to the command and a different one to the options?

Thanks.

**Comment by binarymist** [comment]
I can't seem to find a `usage:` key?

**Comment by binarymist** [comment]
Although if we have the two imports the opposite way around to what the [docs](https://github.com/nexdrew/yargonaut#install) specify, we get a yargs instance.

**Comment by nexdrew** [comment]
@binarymist Hi 👋 unfortunately I am no longer maintaining yargonaut and it may be incompatible with the latest version of yargs. [Please read this for more info.](https://github.com/nexdrew/yargonaut/issues/9#issuecomment-351807371)

**Comment by binarymist** [comment]
Ok, so basicallly the answer is to move to sywac. Although it's really anoying as I've just spent a couple of days on this, I do understand your reasoning and it makes sense. I've seen quite a few times project founders do this, and the second, third project in the same catagory inherits all the learnings (same mistakes not made) from the former projects. I have a few questions:

* There are very few colaborators on sywac, in fact, you're essentially the only one. What do you think the reason for this is?
* How long are you planning on maintaining sywac?
* What are your thoughts for why the uptake has been so slow on sywac, I've also never heard of it before now, which is dissapointing
* Does sywac resolve all the issues I've mentioned above?
* In the [comparison matirx](http://sywac.io/about/comparison-matrix.html)  it states that Command Executiion is awaiting completion, does that mean it's not done, or does that mean awaits in the technical sense?
* Does sywac allow for removing `[boolean]` for `-v` and `-h`?
* Does sywac styling support everything in chalk, rgb/hex values, etc?

I'll create a branch and have a crack at sywac, the docs look good on first appearance, although a lot missing. Do you have a contibuting guide?

**Comment by onury** [comment]
I agree that content & styles should be handled separately. 
But yargs' API makes it almost impossible to style the output properly.
At least some API should be added to "help" enable colors.

**Comment by davidkjackson54** [comment]
Has sywac been abandoned? I don't see any movement on it for over 6 months and the doc is minimal.

**Comment by nexdrew** [comment]
@davidkjackson54 No, sywac has not been abandoned. It's at a relatively stable point and I use it for all my own CLIs. I just haven't had time to work on the docs or road-mapped features in a long time, and no one else has volunteered to help. I am still maintaining the project and will continue to do so for the foreseeable future.

**Comment by davidkjackson54** [comment]
Thanks that is great to know.  I have a need to be able to support positional parameters for example:
cli.js  jobs status --jname   

where jobs and status are both positional parameters and jname is a required subparm. 
I know yargs can handle this but I haven't been able to find any documented on how to accomplish this in sywac.  I also need to have the help auto generated for this.   So a user could enter
cli.js --help
cli.js jobs --help
cli,js jobs status --help 

Are there any samples of how i can accomplish this available?

**Comment by nexdrew** [comment]
Are you asking for yargs or sywac? If you are asking how to do this in sywac, please open an issue there.

**Comment by davidkjackson54** [comment]
Done
