### ISSUE TITLE
Potential Issue—Double flags shown

### ISSUE THREAD

**Issue by jameswomack** [bcoe/yargs#267]
Hey @bcoe !

I've a special case in which I've written a testing suite that is capable of testing itself. In this case, Yargs shows the flags as double rather than single. I've a simple example here with all the extraneous elements removed:

https://github.com/jameswomack/mocha-yargs

**Comment by nexdrew** [comment]
Don't mean to steal anyone's thunder, but I don't think this is a yargs problem. Adding `console.dir(process.argv)` to your test clearly shows that the options are duplicated before yargs has a chance to parse them. Any CLI parser that interprets duplicate options as an array (like minimist) instead of just taking the first or last value (like commander) will exhibit the same behavior.

This looks like a [mocha bug](https://github.com/mochajs/mocha/commit/3a718587115a8578c1d0a283bbe214d09a35831b) to me. Notice there that `getOptions()` is called twice - first in `bin/mocha` and then again in `bin/_mocha`. If you remove either one of those, your test works.

**Comment by nexdrew** [comment]
Note that I've [submitted a PR](https://github.com/mochajs/mocha/pull/1910) to mocha to fix this.

**Comment by jameswomack** [comment]
There's no thunder to steal—just trying to get to the root of it :)

Based on what you've shown, I'm closing this.

**Comment by nexdrew** [comment]
Cool, thanks @jameswomack.

Sorry if I sounded like a jerk - that was not my intention. I just didn't want to hijack something meant for @bcoe. :confused: I know he stays pretty busy these days.

Otherwise, thanks for reporting (and closing) this issue! :+1:

**Comment by jameswomack** [comment]
Heh, it's hard communicating w/ text sometimes :)

On Tue, Sep 29, 2015 at 8:51 AM, Andrew Goode <notifications@github.com>
wrote:

> Cool, thanks @jameswomack <https://github.com/jameswomack>.
>
> Sorry if I sounded like a jerk - that was not my intention. I just didn't
> want to hijack something meant for @bcoe <https://github.com/bcoe>. [image:
> :confused:] I know he stays pretty busy these days.
>
> Otherwise, thanks for reporting (and closing) this issue! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcoe/yargs/issues/267#issuecomment-144100922>.
>



-- 
James J. Womack
Senior Software Engineer/Architect
Netflix
