### ISSUE TITLE
Passing options with more than one char

### ISSUE THREAD

**Issue by jameswomack** [bcoe/yargs#311]
Hey yo! :star: 
Thanks for everything you've all done on Yargs, I really appreciate it. I've a weird case I'm interested in knowing more about.

This works:

```
function start (argv) {
  if (argv) {
    argv.c && (this.opts.foo.command = argv.c)
  }
}

const Foo = {
  start : start
}

if (!module.parent) {
  const argv = Yargs
        .option('c', {
          alias: 'foo-command',
          default: opts.foo.command
        })
        .argv

  Foo.start(argv)
}

```

This doesn't

```
function start (argv) {
  if (argv) {
    argv.fc && (this.opts.foo.command = argv.fc)
  }
}

const Foo = {
  start : start
}

if (!module.parent) {
  const argv = Yargs
        .option('fc', {
          alias: 'foo-command',
          default: opts.foo.command
        })
        .argv

  Foo.start(argv)
}

```

... and no warning is logged, no exception is thrown.

**Comment by maxrimue** [comment]
What do you mean by "this doesn't work"? Do you mean that `argv.fc` doesn't equal `true`? Can you provide the CLI input you pass to your file?

**Comment by jameswomack** [comment]
Certainly @maxrimue, I genuinely didn't realize "didn't work" could mean more than one thing in this context. Here we go:

If I define an options with multiple chars, such as "fc" (code example above), and the user calls the program as `foo -fc bar` or `foo -fc=bar`, `argv.fc` is falsy. I.e., `argv.fc !== 'bar'`.

Given how I defined the options block, and given the documentation regarding passing arguments via the CLI, I expect `argv.fc` to equal `'bar'` if the user calls `foo -fc bar` or `foo -fc=bar`.

To be clear, I'm not complaining. I know Ben and I'm super grateful for this module. I'm just trying to understand what's happening here. I thought it'd be an easy answer, but I will just fork and debug the source.

**Comment by maxrimue** [comment]
@jameswomack Actually, I don't think this is yargs' fault as in a code mistake here, I think the problem is the following:

When you use one dash, each char gets parsed as an option, this is not just how yargs, but in fact (almost) every CLI program works. Say, you type `-fc`, yargs will parse this as `f __and__ c options are true`. What you want is <i>one</i> option that is called 'fc', so you need to call it via `--fc`, then yargs will parse it as `fc option is true`. Maybe I'm overseeing something here, but I think that is the problem you are facing here. Also, I don't see this as a complaint, filing issues when you don't understand something is just fine, that's what they're for. I hope I could help you with this response.

**Comment by nexdrew** [comment]
@maxrimue is correct. Single dash args are reserved for single character flags only, and they can be grouped together on the command line for convenience. Any option/alias with more than one character requires a two dash flag on the command line.

**Comment by jameswomack** [comment]
@maxrimue @nexdrew That makes complete sense! It's funny, I use grouped flags everyday and yet that didn't occur to me here :smile_cat:. Thanks for pointing it out to me.

**Comment by nexdrew** [comment]
@jameswomack No problem, happens to the best of us! :grinning:
