### ISSUE TITLE
Installing yargs globally

### ISSUE THREAD

**Issue by jpsala** [bcoe/yargs#334]
Hi, I don't know if this is the right place to ask.
I installed yargs globally but can't use it, I'm new to node, am I doing something wrong?

**Comment by nexdrew** [comment]
@jpsala Hey, that's a great question! I think our docs probably take it for granted that users understand what yargs helps them do - which is a poor assumption to make - so we focus on describing _how_ to use yargs rather than describing _what_ yargs is and its main objective.

## Description

Let me see if I can answer your question. In short, yargs is not a package intended for global installation. Rather, yargs is a library that helps you build **your** CLI program that is meant to be installed globally.

When we say "install globally", we really just mean install an npm package that has one or more binary modules that allow it to be run as a CLI program, added to your system's PATH. So it's "global" in the sense that, once it's installed, it can be run from anywhere on your system, just as you would run `git` or `ssh` or `npm`, because they're on the PATH that the system uses to find programs to run when you type a command on the command line.

So getting back to yargs, it's intended to be a dependency that your code `require()`s to help build your own command line interface, which is typically just accepting arguments and writing stuff to stdout. yargs makes it easy to define what type of arguments your CLI accepts and will build help/usage text for your program on your behalf. It also gives you a simple way to access the arguments to your program, either by name (for "flag" based options) or by index (for "flagless" arguments), all from a simple object called `argv`.

## Example Code

Here's a quick example.

```js
// file name: hello.js
var argv = require('yargs')
  .usage('Usage: $0 [options] <name>')
  .option('t', {
    alias: 'thanks',
    describe: 'Print a "thanks" message too',
    type: 'boolean'
  })
  .help('h').alias('h', 'help')
  .demand(1) // at least one "flagless" argument required for <name>
  .example('$0 Bob', 'Prints: Hello Bob!')
  .example('$0 -t Bob', 'Prints: Hello Bob! Thanks for using yargs!')
  .example('$0 -h', 'Prints this help text')
  .argv // this actually parses the arguments to the program and returns them as an object
var msg = 'Hello ' + argv._[0] + '!' // flagless arguments are put in the argv._ array
if (argv.thanks) msg += ' Thanks for using yargs!' // flag arguments can be referenced by name or alias
console.log(msg)
```

When we run our program without any arguments, we get help text and an error message because our program requires at least one flagless argument:

```
$ node hello.js
Usage: hello.js [options] <name>

Options:
  -t, --thanks  Print a "thanks" message too                           [boolean]
  -h, --help    Show help                                              [boolean]

Examples:
  hello.js Bob     Prints: Hello Bob!
  hello.js -t Bob  Prints: Hello Bob! Thanks for using yargs!
  hello.js -h      Prints this help text

Not enough non-option arguments: got 0, need at least 1
```

When we run it with one flagless argument and no flag options, we get the hello message expected:

```
$ node hello.js Jon
Hello Jon!
```

When we run it with one flagless argument and our boolean flag option `-t` or `--thanks`, we get the hello message with the additional thanks message:

```
$ node hello.js -t Jon
Hello Jon! Thanks for using yargs!
```

Running it with just the `-h` or `--help` option, we get the help text:

```
$ node hello.js --help
Usage: hello.js [options] <name>

Options:
  -t, --thanks  Print a "thanks" message too                           [boolean]
  -h, --help    Show help                                              [boolean]

Examples:
  hello.js Bob     Prints: Hello Bob!
  hello.js -t Bob  Prints: Hello Bob! Thanks for using yargs!
  hello.js -h      Prints this help text
```

## Defining a Global Package

If we want to be able to run our program without explicitly calling `node`, then we just make our `hello.js` executable (`chmod +x hello.js`) and add this to the top:

```
#!/usr/bin/env node
// javascript code from above goes here
```

So we can now just run `hello.js` from the command line:

```
$ ./hello.js Paul
Hello Paul!
```

And to round it out, we can add a [`"bin"` section to our `package.json` file](https://docs.npmjs.com/files/package.json#bin) that will allow our package to be installed globally:

```json
{
  "name": "hello",
  "version": "1.0.0",
  "description": "A simple friendly CLI package",
  "main": "index.js",
  "bin": {
    "hello": "hello.js"
  },
  "dependencies": {
    "yargs": "^3.31.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "hello"
  ],
  "author": "nexdrew",
  "license": "ISC"
}
```

Now if we `npm install -g` this package, npm will add the `hello` program to our PATH.

```
$ npm install -g .
/usr/local/bin/hello -> /usr/local/lib/node_modules/hello/hello.js
$ hello jpsala --thanks 
Hello jpsala! Thanks for using yargs!
```

## End (Phew!)

Hopefully this helps make some sense of yargs and gets you started on the right path. Let us know if you have any more questions. Good luck! :smiley_cat:

**Comment by jpsala** [comment]
Thank you very much for taking time to answer SO kindly!!!!!!!!!!! and congrats for this peace of helpful software! Good luck to you too
