### ISSUE TITLE
Question | group options

### ISSUE THREAD

**Issue by przemyslawpluta** [bcoe/yargs#53]
Is there a way to group options for display with `--help` from:

```js
Usage: app [options]

Options:
  --opt1         option 1                                           [required]
  --opt2         option 2
  --opt3         option 3
  ...
```
... to:
```js
Usage: app [options]

Options:
  --opt1         option 1                                           [required]
  ...

Additional Options: 
  --opt2         option 2
  --opt3         option 3
  ...
```

Thanks.

**Comment by bcoe** [comment]
@przemyslawpluta, I've documented how to create complex nested CLIs in this pull request:

https://github.com/bcoe/yargs/pull/102

My preference would be that, rather than adding a feature that lets us group together multiple sets of option flags, a complex CLI would start to split itself into multiple commands via this nested approach.

What do you think?
